### ISSUE TITLE
How to modify plugin to make it work ?

### ISSUE THREAD

**Issue by happytm** [SmartNodeRules/ESPCoreRules#1]
Continuing from our discussion at ESPeasy forum I was wondering what is involved in striping out existing plugins from ESPeasy to use with your firmware ? Basically I like the idea of core without Configuration GUI and scaling up from there.My most liked feature at ESPeasy is rules engine and plugin system I have hard time compiling under arduino to customize it.

Thanks

**Comment by FanOfHue** [comment]
I no longer use ESP Easy because it's quite a bit too bulky for my projects and i don't like the double-step OTA on my 1MB modules.
My core framework is really just the bare essentials: Wifi/Networking/Engine/Plugins.
But it's aimed for users that know how to develop own code/plugins.

Generic approach would be like:
- wipe all the webgui stuff that is no longer needed
- transform the code from the read plugin call to the write plugin call section so a specific command stores the data into a variable
- use timers and variables in the rule engine to do all the magic

**Comment by happytm** [comment]
Thanks for your help.I will try that.
